# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - eventhostapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install EF Tool
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
          
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Generate scripts
        run: dotnet ef migrations script --startup-project GDC.EventHost.API --project GDC.EventHost.API  -o sql-script.sql

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: migrations-file
          path: ./sql-script.sql
          
      - name: Show directory contents for debugging
        run: |
          pwd
          ls -la
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E16ABC310104D0B943405665A547FD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4F4EB363B0C040F4BA3C1C8235506C46 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A02FC12DE9E744B1A66482A77C456452 }}

      - name: Show directory contents for debugging
        run: |
          pwd
          ls -la

      - name: Download File
        uses: actions/download-artifact@v4
        with:
          name: migrations-file
          
      - name: Display File Contents
        run: cat sql-script.sql
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.2.1
        with:
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.CONNECTION_STRING }}
          # Path to the file used for this action. Supported file types are .sql, .dacpac, or .sqlproj.
          path: ./sql-script.sql

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eventhostapi'
          slot-name: 'Production'
          package: .
          
